pub const MIN_FAN_SPEED: i64 = 20;
pub const FAN_RAMP_STEP: i64 = 10;
pub const FAN_RAMP_STEP_DOWN: i64 = 6;
pub const CONTROL_SLEEP_MS: u64 = 3000;
pub const TEMP_EMERGENCY: i64 = 95;
pub const TEMP_EMA_ALPHA: f64 = 0.4;
pub const SPEED_EMA_ALPHA: f64 = 0.6;
pub const TEMP_JUMP_THRESHOLD: i64 = 4;
pub const FAST_RAMP_UP: i64 = 20;

pub const MAX_FAN_SPEED_PERCENT: i64 = 100;
pub const MIN_TEMP_LIMIT: i64 = 1;
pub const MAX_TEMP_LIMIT: i64 = 110;
pub const MAX_SENSOR_RPM: i64 = 7000;

pub const DEFAULT_RAMP_UP_STEP: i64 = FAN_RAMP_STEP;
pub const DEFAULT_RAMP_DOWN_STEP: i64 = FAN_RAMP_STEP_DOWN;
pub const DEFAULT_MODE: &str = "office";
pub const DEFAULT_CPU_HYSTERESIS_BANDWIDTH: i64 = 5;
pub const DEFAULT_GPU_HYSTERESIS_BANDWIDTH: i64 = 5;
pub const DEFAULT_CPU_FAN_MAX_PERCENT: i64 = 55;
pub const DEFAULT_GPU_FAN_MAX_PERCENT: i64 = 45;
pub const DEFAULT_GPU_LINKAGE_THRESHOLD: i64 = 83;
pub const DEFAULT_GPU_LINKAGE_BOOST: i64 = 10;
pub const DEFAULT_MONITOR_SAMPLE_INTERVAL_MS: u64 = 2500;
pub const MIN_MONITOR_SAMPLE_INTERVAL_MS: u64 = 500;
pub const MAX_MONITOR_SAMPLE_INTERVAL_MS: u64 = 60_000;

pub const DEFAULT_CPU_ALERT_THRESHOLD: i64 = 90;
pub const DEFAULT_GPU_ALERT_THRESHOLD: i64 = 90;
pub const DEFAULT_ALERT_CONFIRM_TIMES: u32 = 2;
pub const DEFAULT_ZERO_RPM_THRESHOLD: i64 = 45;
